version: "3"

tasks:
  init:
    desc: Initialize Python with required tools
    cmds:
      - PIPENV_VENV_IN_PROJECT=1 pipenv sync -d

  validate:
    desc: Validate the pre-commit hooks
    cmds:
      - pre-commit install
      - pre-commit run -a

  run:
    desc: Run the Python script
    cmds:
      - PIPENV_VENV_IN_PROJECT=1 pipenv run python main.py
